# Generated by Django 2.2.4 on 2019-08-14 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0006_comment_comment_oy'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='title',
            field=models.CharField(default='Başlık', max_length=50),
        ),
        migrations.AlterField(
            model_name='comment',
            name='comment_oy',
            field=models.CharField(default='Oy', max_length=50),
        ),
    ]
