# Generated by Django 2.2.4 on 2019-08-14 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0007_auto_20190814_1451'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='comment_oy',
            field=models.CharField(blank=True, default='Oy', max_length=50, null=True),
        ),
    ]
