# Generated by Django 2.2.4 on 2019-08-14 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0009_comment_comment_script'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='comment_script',
            field=models.CharField(default=' ', max_length=100),
        ),
    ]
