# Generated by Django 2.2.4 on 2019-08-14 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0010_auto_20190814_1724'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='article_aciklama',
            field=models.CharField(default='deneme', editable=False, max_length=50),
        ),
    ]
