# Generated by Django 2.2.4 on 2019-08-14 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0011_article_article_aciklama'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='article_aciklama',
            field=models.CharField(default='Açıklamalar Burada Görünür', max_length=50),
        ),
    ]
