# Generated by Django 2.2.4 on 2019-08-14 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0012_auto_20190814_1821'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prohelp', models.CharField(default='Yapacaklarını söyleyeyim.', max_length=50)),
                ('title', models.CharField(default='Ürün Adı', max_length=50)),
                ('pro_content', models.CharField(max_length=200, verbose_name='Ürün Açıklaması')),
                ('pro_date', models.DateTimeField(auto_now_add=True)),
                ('article_image', models.FileField(blank=True, null=True, upload_to='', verbose_name='Bir fotoğraf ekle. (Unidecimal 180*180 boyutları tavsiye ediyor)')),
            ],
            options={
                'ordering': ['-pro_date'],
            },
        ),
    ]
