# Generated by Django 2.2.4 on 2019-08-14 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0013_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='prohelp',
            field=models.CharField(default='Buraya bir uyarı bırakabilirsin (Sadece sen göreceksin)', max_length=50),
        ),
    ]
