# Generated by Django 2.2.4 on 2019-08-14 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0014_auto_20190814_1841'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='prohelp',
            field=models.CharField(default='Buraya bir uyarı bırak.(Sadece sen göreceksin)', max_length=50),
        ),
    ]
