# Generated by Django 2.2.4 on 2019-08-14 19:35

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0017_auto_20190814_1854'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='kisim1',
            field=ckeditor.fields.RichTextField(default='Açıklamalar Burada Görünür'),
        ),
        migrations.AddField(
            model_name='article',
            name='kisim2',
            field=ckeditor.fields.RichTextField(default='Açıklamalar Burada Görünür'),
        ),
        migrations.AddField(
            model_name='article',
            name='kisim3',
            field=ckeditor.fields.RichTextField(default='Açıklamalar Burada Görünür'),
        ),
        migrations.AddField(
            model_name='article',
            name='kisim4',
            field=ckeditor.fields.RichTextField(default='Açıklamalar Burada Görünür'),
        ),
        migrations.AddField(
            model_name='article',
            name='kisim5',
            field=ckeditor.fields.RichTextField(default='Açıklamalar Burada Görünür'),
        ),
        migrations.AddField(
            model_name='article',
            name='kisim6',
            field=ckeditor.fields.RichTextField(default='Açıklamalar Burada Görünür'),
        ),
    ]
