# Generated by Django 2.2.4 on 2019-08-14 19:44

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0018_auto_20190814_2235'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='kisim1',
            field=ckeditor.fields.RichTextField(default='Açıklamalar Burada Görünür', null=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='kisim2',
            field=ckeditor.fields.RichTextField(default='Açıklamalar Burada Görünür', null=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='kisim3',
            field=ckeditor.fields.RichTextField(default='Açıklamalar Burada Görünür', null=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='kisim4',
            field=ckeditor.fields.RichTextField(default='Açıklamalar Burada Görünür', null=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='kisim5',
            field=ckeditor.fields.RichTextField(default='Açıklamalar Burada Görünür', null=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='kisim6',
            field=ckeditor.fields.RichTextField(default='Açıklamalar Burada Görünür', null=True),
        ),
    ]
