# Generated by Django 2.2.4 on 2019-08-14 19:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0019_auto_20190814_2244'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='kisim1',
        ),
        migrations.RemoveField(
            model_name='article',
            name='kisim2',
        ),
        migrations.RemoveField(
            model_name='article',
            name='kisim3',
        ),
        migrations.RemoveField(
            model_name='article',
            name='kisim4',
        ),
        migrations.RemoveField(
            model_name='article',
            name='kisim5',
        ),
        migrations.RemoveField(
            model_name='article',
            name='kisim6',
        ),
    ]
