# Generated by Django 2.0 on 2019-08-16 16:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0020_auto_20190814_2247'),
    ]

    operations = [
        migrations.CreateModel(
            name='help',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('help_name', models.CharField(default='isim', max_length=50)),
                ('help_mail', models.EmailField(default='Email', max_length=50)),
                ('help_date', models.DateField(auto_now_add=True)),
                ('help_title', models.CharField(default='konu', max_length=50)),
                ('help_content', models.TextField(default='Sizi dinliyoruz', max_length=500)),
                ('article', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='article.Article', verbose_name='Makale')),
            ],
            options={
                'ordering': ['-help_date'],
            },
        ),
        migrations.AlterField(
            model_name='comment',
            name='comment_oy',
            field=models.CharField(default='Oy', max_length=50),
        ),
    ]
